---
- hosts: all
  tasks:

    - name: Install Docker vars
      apt:
        name: "{{ packs }}"
        update_cache: true
        state: present
      vars:
        packs:
          - ca-certificates
          - apt-transport-https
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Install Docker packs
      apt:
        name: "{{ packs }}"
        update_cache: true
        state: present
      vars:
        packs:
          - docker-ce
          - docker-ce-cli
          - containerd.io