---
- hosts: all
  tasks:
    - name: Git clone repo
      git:
        repo: 'https://github.com/FreddieMcHeart/test.me'
        dest: /home/test.me

    - name: Deploy FluentD and apache
      shell: |
        kubectl apply -f /home/test.me/kubernetes/fluentd.yaml
        kubectl apply -f /home/test.me/kubernetes/apache.yaml