---
- hosts: all
  tasks:
    - name: Git clone repo
      git:
        repo: 'https://github.com/FreddieMcHeart/test.me'
        dest: /home/test.me

    - name: Deploy FluentD
      k8s:
        state: present
        src: /home/test.me/kubernetes/fluentd.yaml

    - name: Deploy apache
      k8s:
        state: present
        src: /home/test.me/kubernetes/apache.yaml
