- hosts: all
  tasks:

    - name: Install minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube


    - name: Make minikube executable
      file: dest=/usr/local/bin/minikube mode=a+x

    - name: Start minikube
      shell: |
        minikube start --vm-driver=none