- hosts: all
  tasks:

    - name: Install dependencies
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        mv minikube /usr/local/bin/
        minikube start --vm-driver=none